//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Implementation
{
    
    #region ChangeRequest
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ChangeRequest :
        global::LightSwitchApplication.ChangeRequest.DetailsClass.IImplementation
    {
        partial void OnChangeRequest_EmployeeChanged()
        {
            this.___OnPropertyChanged("ChangeRequest_Employee");
            this.___OnPropertyChanged("RaisedBy");
        }
        
        partial void OnChangeRequestStatus_ChangeRequestChanged()
        {
            this.___OnPropertyChanged("ChangeRequestStatus_ChangeRequest");
            this.___OnPropertyChanged("ChangeRequestStatus");
        }
        
        partial void OnChangeRequest_DocumentVersionChanged()
        {
            this.___OnPropertyChanged("ChangeRequest_DocumentVersion");
            this.___OnPropertyChanged("DocumentVersion");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnReferenceChanged()
        {
            this.___OnPropertyChanged("Reference");
        }
        
        partial void OnChangeRequestTitleChanged()
        {
            this.___OnPropertyChanged("ChangeRequestTitle");
        }
        
        partial void OnChangeRequestDescriptionChanged()
        {
            this.___OnPropertyChanged("ChangeRequestDescription");
        }
        
        partial void OnDateRaisedChanged()
        {
            this.___OnPropertyChanged("DateRaised");
        }
        
        partial void OnTargetClosureDateChanged()
        {
            this.___OnPropertyChanged("TargetClosureDate");
        }
        
        partial void OnDateClosedChanged()
        {
            this.___OnPropertyChanged("DateClosed");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ChangeRequest.DetailsClass.IImplementation.RaisedBy
        {
            get
            {
                return this.RaisedBy;
            }
            set
            {
                this.RaisedBy = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __RaisedBy
        {
            get
            {
                if (this.___RaisedBy == null)
                {
                    this.___RaisedBy = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "RaisedBy",
                        new string[] { "ChangeRequest_Employee" },
                        e => global::System.Object.Equals(e.Id, this.ChangeRequest_Employee),
                        () => this._RaisedBy,
                        e => this._RaisedBy = e);
                }
                return this.___RaisedBy;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___RaisedBy;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ChangeRequest.DetailsClass.IImplementation.ChangeRequestStatus
        {
            get
            {
                return this.ChangeRequestStatus;
            }
            set
            {
                this.ChangeRequestStatus = (global::LightSwitchApplication.Implementation.ChangeRequestStatus)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ChangeRequestStatus> __ChangeRequestStatus
        {
            get
            {
                if (this.___ChangeRequestStatus == null)
                {
                    this.___ChangeRequestStatus = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ChangeRequestStatus>(
                        this,
                        "ChangeRequestStatus",
                        new string[] { "ChangeRequestStatus_ChangeRequest" },
                        e => global::System.Object.Equals(e.Id, this.ChangeRequestStatus_ChangeRequest),
                        () => this._ChangeRequestStatus,
                        e => this._ChangeRequestStatus = e);
                }
                return this.___ChangeRequestStatus;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ChangeRequestStatus> ___ChangeRequestStatus;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ChangeRequest.DetailsClass.IImplementation.DocumentVersion
        {
            get
            {
                return this.DocumentVersion;
            }
            set
            {
                this.DocumentVersion = (global::LightSwitchApplication.Implementation.DocumentVersion)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.DocumentVersion> __DocumentVersion
        {
            get
            {
                if (this.___DocumentVersion == null)
                {
                    this.___DocumentVersion = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.DocumentVersion>(
                        this,
                        "DocumentVersion",
                        new string[] { "ChangeRequest_DocumentVersion" },
                        e => global::System.Object.Equals(e.Id, this.ChangeRequest_DocumentVersion),
                        () => this._DocumentVersion,
                        e => this._DocumentVersion = e);
                }
                return this.___DocumentVersion;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.DocumentVersion> ___DocumentVersion;
        
    }
    #endregion
    
    #region ChangeRequestStatus
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ChangeRequestStatus :
        global::LightSwitchApplication.ChangeRequestStatus.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnStatusChanged()
        {
            this.___OnPropertyChanged("Status");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ChangeRequestStatus.DetailsClass.IImplementation.ChangeRequests
        {
            get
            {
                return this.ChangeRequests;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeRequest> __ChangeRequests
        {
            get
            {
                if (this.___ChangeRequests == null)
                {
                    this.___ChangeRequests = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeRequest>(
                        this,
                        "ChangeRequests",
                        () => this._ChangeRequests,
                        e => global::System.Object.Equals(e.ChangeRequestStatus_ChangeRequest, this.Id));
                }
                return this.___ChangeRequests;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeRequest> ___ChangeRequests;
        
    }
    #endregion
    
    #region Document
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Document :
        global::LightSwitchApplication.Document.DetailsClass.IImplementation
    {
        partial void OnDocumentType_DocumentChanged()
        {
            this.___OnPropertyChanged("DocumentType_Document");
            this.___OnPropertyChanged("DocumentType");
        }
        
        partial void OnDocument_EmployeeChanged()
        {
            this.___OnPropertyChanged("Document_Employee");
            this.___OnPropertyChanged("DocumentOwner");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnDocumentTitleChanged()
        {
            this.___OnPropertyChanged("DocumentTitle");
        }
        
        partial void OnReferenceChanged()
        {
            this.___OnPropertyChanged("Reference");
        }
        
        partial void OnInUseChanged()
        {
            this.___OnPropertyChanged("InUse");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Document.DetailsClass.IImplementation.DocumentType
        {
            get
            {
                return this.DocumentType;
            }
            set
            {
                this.DocumentType = (global::LightSwitchApplication.Implementation.DocumentType)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.DocumentType> __DocumentType
        {
            get
            {
                if (this.___DocumentType == null)
                {
                    this.___DocumentType = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.DocumentType>(
                        this,
                        "DocumentType",
                        new string[] { "DocumentType_Document" },
                        e => global::System.Object.Equals(e.Id, this.DocumentType_Document),
                        () => this._DocumentType,
                        e => this._DocumentType = e);
                }
                return this.___DocumentType;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.DocumentType> ___DocumentType;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Document.DetailsClass.IImplementation.DocumentOwner
        {
            get
            {
                return this.DocumentOwner;
            }
            set
            {
                this.DocumentOwner = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __DocumentOwner
        {
            get
            {
                if (this.___DocumentOwner == null)
                {
                    this.___DocumentOwner = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "DocumentOwner",
                        new string[] { "Document_Employee" },
                        e => global::System.Object.Equals(e.Id, this.Document_Employee),
                        () => this._DocumentOwner,
                        e => this._DocumentOwner = e);
                }
                return this.___DocumentOwner;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___DocumentOwner;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Document.DetailsClass.IImplementation.DocumentVersions
        {
            get
            {
                return this.DocumentVersions;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.DocumentVersion> __DocumentVersions
        {
            get
            {
                if (this.___DocumentVersions == null)
                {
                    this.___DocumentVersions = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.DocumentVersion>(
                        this,
                        "DocumentVersions",
                        () => this._DocumentVersions,
                        e => global::System.Object.Equals(e.DocumentVersion_Document, this.Id));
                }
                return this.___DocumentVersions;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.DocumentVersion> ___DocumentVersions;
        
    }
    #endregion
    
    #region DocumentType
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class DocumentType :
        global::LightSwitchApplication.DocumentType.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnDocumentTypeCodeChanged()
        {
            this.___OnPropertyChanged("DocumentTypeCode");
        }
        
        partial void OnDocumentTypeDescriptionChanged()
        {
            this.___OnPropertyChanged("DocumentTypeDescription");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.DocumentType.DetailsClass.IImplementation.Documents
        {
            get
            {
                return this.Documents;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Document> __Documents
        {
            get
            {
                if (this.___Documents == null)
                {
                    this.___Documents = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Document>(
                        this,
                        "Documents",
                        () => this._Documents,
                        e => global::System.Object.Equals(e.DocumentType_Document, this.Id));
                }
                return this.___Documents;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Document> ___Documents;
        
    }
    #endregion
    
    #region DocumentVersionApproval
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class DocumentVersionApproval :
        global::LightSwitchApplication.DocumentVersionApproval.DetailsClass.IImplementation
    {
        partial void OnDocumentVersionApproval_DocumentVersionChanged()
        {
            this.___OnPropertyChanged("DocumentVersionApproval_DocumentVersion");
            this.___OnPropertyChanged("DocumentVersion");
        }
        
        partial void OnDocumentVersionApproval_EmployeeChanged()
        {
            this.___OnPropertyChanged("DocumentVersionApproval_Employee");
            this.___OnPropertyChanged("Approver");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnApprovalStatusChanged()
        {
            this.___OnPropertyChanged("ApprovalStatus");
        }
        
        partial void OnApprovalStatusDateChanged()
        {
            this.___OnPropertyChanged("ApprovalStatusDate");
        }
        
        partial void OnApproverCommentsChanged()
        {
            this.___OnPropertyChanged("ApproverComments");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.DocumentVersionApproval.DetailsClass.IImplementation.DocumentVersion
        {
            get
            {
                return this.DocumentVersion;
            }
            set
            {
                this.DocumentVersion = (global::LightSwitchApplication.Implementation.DocumentVersion)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.DocumentVersion> __DocumentVersion
        {
            get
            {
                if (this.___DocumentVersion == null)
                {
                    this.___DocumentVersion = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.DocumentVersion>(
                        this,
                        "DocumentVersion",
                        new string[] { "DocumentVersionApproval_DocumentVersion" },
                        e => global::System.Object.Equals(e.Id, this.DocumentVersionApproval_DocumentVersion),
                        () => this._DocumentVersion,
                        e => this._DocumentVersion = e);
                }
                return this.___DocumentVersion;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.DocumentVersion> ___DocumentVersion;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.DocumentVersionApproval.DetailsClass.IImplementation.Approver
        {
            get
            {
                return this.Approver;
            }
            set
            {
                this.Approver = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __Approver
        {
            get
            {
                if (this.___Approver == null)
                {
                    this.___Approver = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "Approver",
                        new string[] { "DocumentVersionApproval_Employee" },
                        e => global::System.Object.Equals(e.Id, this.DocumentVersionApproval_Employee),
                        () => this._Approver,
                        e => this._Approver = e);
                }
                return this.___Approver;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___Approver;
        
    }
    #endregion
    
    #region DocumentVersionHolder
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class DocumentVersionHolder :
        global::LightSwitchApplication.DocumentVersionHolder.DetailsClass.IImplementation
    {
        partial void OnDocumentVersionHolder_DocumentVersionChanged()
        {
            this.___OnPropertyChanged("DocumentVersionHolder_DocumentVersion");
            this.___OnPropertyChanged("DocumentVersion");
        }
        
        partial void OnDocumentVersionHolder_EmployeeChanged()
        {
            this.___OnPropertyChanged("DocumentVersionHolder_Employee");
            this.___OnPropertyChanged("CopyHolder");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnDateDistributedToChanged()
        {
            this.___OnPropertyChanged("DateDistributedTo");
        }
        
        partial void OnDateAcknowledgedChanged()
        {
            this.___OnPropertyChanged("DateAcknowledged");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.DocumentVersionHolder.DetailsClass.IImplementation.DocumentVersion
        {
            get
            {
                return this.DocumentVersion;
            }
            set
            {
                this.DocumentVersion = (global::LightSwitchApplication.Implementation.DocumentVersion)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.DocumentVersion> __DocumentVersion
        {
            get
            {
                if (this.___DocumentVersion == null)
                {
                    this.___DocumentVersion = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.DocumentVersion>(
                        this,
                        "DocumentVersion",
                        new string[] { "DocumentVersionHolder_DocumentVersion" },
                        e => global::System.Object.Equals(e.Id, this.DocumentVersionHolder_DocumentVersion),
                        () => this._DocumentVersion,
                        e => this._DocumentVersion = e);
                }
                return this.___DocumentVersion;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.DocumentVersion> ___DocumentVersion;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.DocumentVersionHolder.DetailsClass.IImplementation.CopyHolder
        {
            get
            {
                return this.CopyHolder;
            }
            set
            {
                this.CopyHolder = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __CopyHolder
        {
            get
            {
                if (this.___CopyHolder == null)
                {
                    this.___CopyHolder = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "CopyHolder",
                        new string[] { "DocumentVersionHolder_Employee" },
                        e => global::System.Object.Equals(e.Id, this.DocumentVersionHolder_Employee),
                        () => this._CopyHolder,
                        e => this._CopyHolder = e);
                }
                return this.___CopyHolder;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___CopyHolder;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.DocumentVersionHolder.DetailsClass.IImplementation.DocumentVersionReviews
        {
            get
            {
                return this.DocumentVersionReviews;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.DocumentVersionReview> __DocumentVersionReviews
        {
            get
            {
                if (this.___DocumentVersionReviews == null)
                {
                    this.___DocumentVersionReviews = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.DocumentVersionReview>(
                        this,
                        "DocumentVersionReviews",
                        () => this._DocumentVersionReviews,
                        e => global::System.Object.Equals(e.DocumentVersionReview_DocumentVersionHolder, this.Id));
                }
                return this.___DocumentVersionReviews;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.DocumentVersionReview> ___DocumentVersionReviews;
        
    }
    #endregion
    
    #region DocumentVersionReview
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class DocumentVersionReview :
        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.IImplementation
    {
        partial void OnDocumentVersionReview_DocumentVersionHolderChanged()
        {
            this.___OnPropertyChanged("DocumentVersionReview_DocumentVersionHolder");
            this.___OnPropertyChanged("DocumentVersionHolder");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnDateDueChanged()
        {
            this.___OnPropertyChanged("DateDue");
        }
        
        partial void OnDateCompletedChanged()
        {
            this.___OnPropertyChanged("DateCompleted");
        }
        
        partial void OnOutcomeChanged()
        {
            this.___OnPropertyChanged("Outcome");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.DocumentVersionReview.DetailsClass.IImplementation.DocumentVersionHolder
        {
            get
            {
                return this.DocumentVersionHolder;
            }
            set
            {
                this.DocumentVersionHolder = (global::LightSwitchApplication.Implementation.DocumentVersionHolder)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.DocumentVersionHolder> __DocumentVersionHolder
        {
            get
            {
                if (this.___DocumentVersionHolder == null)
                {
                    this.___DocumentVersionHolder = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.DocumentVersionHolder>(
                        this,
                        "DocumentVersionHolder",
                        new string[] { "DocumentVersionReview_DocumentVersionHolder" },
                        e => global::System.Object.Equals(e.Id, this.DocumentVersionReview_DocumentVersionHolder),
                        () => this._DocumentVersionHolder,
                        e => this._DocumentVersionHolder = e);
                }
                return this.___DocumentVersionHolder;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.DocumentVersionHolder> ___DocumentVersionHolder;
        
    }
    #endregion
    
    #region DocumentVersion
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class DocumentVersion :
        global::LightSwitchApplication.DocumentVersion.DetailsClass.IImplementation
    {
        partial void OnDocumentVersion_DocumentChanged()
        {
            this.___OnPropertyChanged("DocumentVersion_Document");
            this.___OnPropertyChanged("Document");
        }
        
        partial void OnDocumentVersion_EmployeeChanged()
        {
            this.___OnPropertyChanged("DocumentVersion_Employee");
            this.___OnPropertyChanged("Author");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnMajorVersionNumberChanged()
        {
            this.___OnPropertyChanged("MajorVersionNumber");
        }
        
        partial void OnMinorVersionNumberChanged()
        {
            this.___OnPropertyChanged("MinorVersionNumber");
        }
        
        partial void OnChangesChanged()
        {
            this.___OnPropertyChanged("Changes");
        }
        
        partial void OnEffectiveDateChanged()
        {
            this.___OnPropertyChanged("EffectiveDate");
        }
        
        partial void OnDocumentStatusChanged()
        {
            this.___OnPropertyChanged("DocumentStatus");
        }
        
        partial void OnDocumentNameChanged()
        {
            this.___OnPropertyChanged("DocumentName");
        }
        
        partial void OnStoredDocumentChanged()
        {
            this.___OnPropertyChanged("StoredDocument");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.DocumentVersion.DetailsClass.IImplementation.Document
        {
            get
            {
                return this.Document;
            }
            set
            {
                this.Document = (global::LightSwitchApplication.Implementation.Document)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Document> __Document
        {
            get
            {
                if (this.___Document == null)
                {
                    this.___Document = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Document>(
                        this,
                        "Document",
                        new string[] { "DocumentVersion_Document" },
                        e => global::System.Object.Equals(e.Id, this.DocumentVersion_Document),
                        () => this._Document,
                        e => this._Document = e);
                }
                return this.___Document;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Document> ___Document;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.DocumentVersion.DetailsClass.IImplementation.Author
        {
            get
            {
                return this.Author;
            }
            set
            {
                this.Author = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __Author
        {
            get
            {
                if (this.___Author == null)
                {
                    this.___Author = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "Author",
                        new string[] { "DocumentVersion_Employee" },
                        e => global::System.Object.Equals(e.Id, this.DocumentVersion_Employee),
                        () => this._Author,
                        e => this._Author = e);
                }
                return this.___Author;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___Author;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.DocumentVersion.DetailsClass.IImplementation.DocumentVersionApprovals
        {
            get
            {
                return this.DocumentVersionApprovals;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.DocumentVersionApproval> __DocumentVersionApprovals
        {
            get
            {
                if (this.___DocumentVersionApprovals == null)
                {
                    this.___DocumentVersionApprovals = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.DocumentVersionApproval>(
                        this,
                        "DocumentVersionApprovals",
                        () => this._DocumentVersionApprovals,
                        e => global::System.Object.Equals(e.DocumentVersionApproval_DocumentVersion, this.Id));
                }
                return this.___DocumentVersionApprovals;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.DocumentVersionApproval> ___DocumentVersionApprovals;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.DocumentVersion.DetailsClass.IImplementation.DocumentVersionHolders
        {
            get
            {
                return this.DocumentVersionHolders;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.DocumentVersionHolder> __DocumentVersionHolders
        {
            get
            {
                if (this.___DocumentVersionHolders == null)
                {
                    this.___DocumentVersionHolders = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.DocumentVersionHolder>(
                        this,
                        "DocumentVersionHolders",
                        () => this._DocumentVersionHolders,
                        e => global::System.Object.Equals(e.DocumentVersionHolder_DocumentVersion, this.Id));
                }
                return this.___DocumentVersionHolders;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.DocumentVersionHolder> ___DocumentVersionHolders;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.DocumentVersion.DetailsClass.IImplementation.ChangeRequests
        {
            get
            {
                return this.ChangeRequests;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeRequest> __ChangeRequests
        {
            get
            {
                if (this.___ChangeRequests == null)
                {
                    this.___ChangeRequests = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeRequest>(
                        this,
                        "ChangeRequests",
                        () => this._ChangeRequests,
                        e => global::System.Object.Equals(e.ChangeRequest_DocumentVersion, this.Id));
                }
                return this.___ChangeRequests;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeRequest> ___ChangeRequests;
        
    }
    #endregion
    
    #region Employee
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Employee :
        global::LightSwitchApplication.Employee.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnLastNameChanged()
        {
            this.___OnPropertyChanged("LastName");
        }
        
        partial void OnFirstNameChanged()
        {
            this.___OnPropertyChanged("FirstName");
        }
        
        partial void OnUserNameChanged()
        {
            this.___OnPropertyChanged("UserName");
        }
        
        partial void OnEmailChanged()
        {
            this.___OnPropertyChanged("Email");
        }
        
        partial void OnCurrentChanged()
        {
            this.___OnPropertyChanged("Current");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.Documents
        {
            get
            {
                return this.Documents;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Document> __Documents
        {
            get
            {
                if (this.___Documents == null)
                {
                    this.___Documents = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Document>(
                        this,
                        "Documents",
                        () => this._Documents,
                        e => global::System.Object.Equals(e.Document_Employee, this.Id));
                }
                return this.___Documents;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Document> ___Documents;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.DocumentVersions
        {
            get
            {
                return this.DocumentVersions;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.DocumentVersion> __DocumentVersions
        {
            get
            {
                if (this.___DocumentVersions == null)
                {
                    this.___DocumentVersions = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.DocumentVersion>(
                        this,
                        "DocumentVersions",
                        () => this._DocumentVersions,
                        e => global::System.Object.Equals(e.DocumentVersion_Employee, this.Id));
                }
                return this.___DocumentVersions;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.DocumentVersion> ___DocumentVersions;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.DocumentVersionHolders
        {
            get
            {
                return this.DocumentVersionHolders;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.DocumentVersionHolder> __DocumentVersionHolders
        {
            get
            {
                if (this.___DocumentVersionHolders == null)
                {
                    this.___DocumentVersionHolders = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.DocumentVersionHolder>(
                        this,
                        "DocumentVersionHolders",
                        () => this._DocumentVersionHolders,
                        e => global::System.Object.Equals(e.DocumentVersionHolder_Employee, this.Id));
                }
                return this.___DocumentVersionHolders;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.DocumentVersionHolder> ___DocumentVersionHolders;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.DocumentVersionApprovals
        {
            get
            {
                return this.DocumentVersionApprovals;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.DocumentVersionApproval> __DocumentVersionApprovals
        {
            get
            {
                if (this.___DocumentVersionApprovals == null)
                {
                    this.___DocumentVersionApprovals = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.DocumentVersionApproval>(
                        this,
                        "DocumentVersionApprovals",
                        () => this._DocumentVersionApprovals,
                        e => global::System.Object.Equals(e.DocumentVersionApproval_Employee, this.Id));
                }
                return this.___DocumentVersionApprovals;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.DocumentVersionApproval> ___DocumentVersionApprovals;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.ChangeRequests
        {
            get
            {
                return this.ChangeRequests;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeRequest> __ChangeRequests
        {
            get
            {
                if (this.___ChangeRequests == null)
                {
                    this.___ChangeRequests = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeRequest>(
                        this,
                        "ChangeRequests",
                        () => this._ChangeRequests,
                        e => global::System.Object.Equals(e.ChangeRequest_Employee, this.Id));
                }
                return this.___ChangeRequests;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ChangeRequest> ___ChangeRequests;
        
    }
    #endregion
    
    #region ApplicationData
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ApplicationData
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.ChangeRequest))
            {
                return new global::LightSwitchApplication.Implementation.ChangeRequest();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ChangeRequestStatus))
            {
                return new global::LightSwitchApplication.Implementation.ChangeRequestStatus();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Document))
            {
                return new global::LightSwitchApplication.Implementation.Document();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.DocumentType))
            {
                return new global::LightSwitchApplication.Implementation.DocumentType();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.DocumentVersionApproval))
            {
                return new global::LightSwitchApplication.Implementation.DocumentVersionApproval();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.DocumentVersionHolder))
            {
                return new global::LightSwitchApplication.Implementation.DocumentVersionHolder();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.DocumentVersionReview))
            {
                return new global::LightSwitchApplication.Implementation.DocumentVersionReview();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.DocumentVersion))
            {
                return new global::LightSwitchApplication.Implementation.DocumentVersion();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Employee))
            {
                return new global::LightSwitchApplication.Implementation.Employee();
            }
            return null;
        }
        
        protected override void InitializeDataServiceContext()
        {
            this.Format.LoadServiceModel = global::LightSwitchApplication.Implementation.ApplicationData.GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
    }
    #endregion
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.ApplicationData();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationData(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../../ApplicationData.svc"));
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.ChangeRequest) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ChangeRequest);
            }
            if (typeof(global::LightSwitchApplication.ChangeRequestStatus) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ChangeRequestStatus);
            }
            if (typeof(global::LightSwitchApplication.Document) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Document);
            }
            if (typeof(global::LightSwitchApplication.DocumentType) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.DocumentType);
            }
            if (typeof(global::LightSwitchApplication.DocumentVersionApproval) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.DocumentVersionApproval);
            }
            if (typeof(global::LightSwitchApplication.DocumentVersionHolder) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.DocumentVersionHolder);
            }
            if (typeof(global::LightSwitchApplication.DocumentVersionReview) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.DocumentVersionReview);
            }
            if (typeof(global::LightSwitchApplication.DocumentVersion) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.DocumentVersion);
            }
            if (typeof(global::LightSwitchApplication.Employee) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Employee);
            }
            return null;
        }
    }
}
