

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class ChangeRequest : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the ChangeRequest entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ChangeRequest()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ChangeRequest(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ChangeRequest> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.ChangeRequest.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ChangeRequest_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ChangeRequest_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.ChangeRequest.DetailsClass.GetValue(this, global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.ChangeRequest.DetailsClass.SetValue(this, global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Reference
        {
            get
            {
                return global::LightSwitchApplication.ChangeRequest.DetailsClass.GetValue(this, global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.Reference);
            }
            set
            {
                global::LightSwitchApplication.ChangeRequest.DetailsClass.SetValue(this, global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.Reference, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Reference_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Reference_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Reference_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ChangeRequestTitle
        {
            get
            {
                return global::LightSwitchApplication.ChangeRequest.DetailsClass.GetValue(this, global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.ChangeRequestTitle);
            }
            set
            {
                global::LightSwitchApplication.ChangeRequest.DetailsClass.SetValue(this, global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.ChangeRequestTitle, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ChangeRequestTitle_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ChangeRequestTitle_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ChangeRequestTitle_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ChangeRequestDescription
        {
            get
            {
                return global::LightSwitchApplication.ChangeRequest.DetailsClass.GetValue(this, global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.ChangeRequestDescription);
            }
            set
            {
                global::LightSwitchApplication.ChangeRequest.DetailsClass.SetValue(this, global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.ChangeRequestDescription, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ChangeRequestDescription_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ChangeRequestDescription_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ChangeRequestDescription_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime DateRaised
        {
            get
            {
                return global::LightSwitchApplication.ChangeRequest.DetailsClass.GetValue(this, global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.DateRaised);
            }
            set
            {
                global::LightSwitchApplication.ChangeRequest.DetailsClass.SetValue(this, global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.DateRaised, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateRaised_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateRaised_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateRaised_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime TargetClosureDate
        {
            get
            {
                return global::LightSwitchApplication.ChangeRequest.DetailsClass.GetValue(this, global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.TargetClosureDate);
            }
            set
            {
                global::LightSwitchApplication.ChangeRequest.DetailsClass.SetValue(this, global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.TargetClosureDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TargetClosureDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TargetClosureDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TargetClosureDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> DateClosed
        {
            get
            {
                return global::LightSwitchApplication.ChangeRequest.DetailsClass.GetValue(this, global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.DateClosed);
            }
            set
            {
                global::LightSwitchApplication.ChangeRequest.DetailsClass.SetValue(this, global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.DateClosed, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateClosed_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateClosed_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateClosed_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.ChangeRequest.DetailsClass.GetValue(this, global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.ChangeRequest.DetailsClass.GetValue(this, global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.ChangeRequest.DetailsClass.GetValue(this, global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.ChangeRequest.DetailsClass.GetValue(this, global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.ChangeRequest.DetailsClass.GetValue(this, global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.ChangeRequest.DetailsClass.SetValue(this, global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Employee RaisedBy
        {
            get
            {
                return global::LightSwitchApplication.ChangeRequest.DetailsClass.GetValue(this, global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.RaisedBy);
            }
            set
            {
                global::LightSwitchApplication.ChangeRequest.DetailsClass.SetValue(this, global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.RaisedBy, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RaisedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RaisedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RaisedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.ChangeRequestStatus ChangeRequestStatus
        {
            get
            {
                return global::LightSwitchApplication.ChangeRequest.DetailsClass.GetValue(this, global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.ChangeRequestStatus);
            }
            set
            {
                global::LightSwitchApplication.ChangeRequest.DetailsClass.SetValue(this, global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.ChangeRequestStatus, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ChangeRequestStatus_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ChangeRequestStatus_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ChangeRequestStatus_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.DocumentVersion DocumentVersion
        {
            get
            {
                return global::LightSwitchApplication.ChangeRequest.DetailsClass.GetValue(this, global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.DocumentVersion);
            }
            set
            {
                global::LightSwitchApplication.ChangeRequest.DetailsClass.SetValue(this, global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.DocumentVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DocumentVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DocumentVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DocumentVersion_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.ChangeRequest,
                global::LightSwitchApplication.ChangeRequest.DetailsClass,
                global::LightSwitchApplication.ChangeRequest.DetailsClass.IImplementation,
                global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass>.Entry
                __ChangeRequestEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass>.Entry(
                    global::LightSwitchApplication.ChangeRequest.DetailsClass.__ChangeRequest_CreateNew,
                    global::LightSwitchApplication.ChangeRequest.DetailsClass.__ChangeRequest_Created,
                    global::LightSwitchApplication.ChangeRequest.DetailsClass.__ChangeRequest_AllowSaveWithErrors);
            private static global::LightSwitchApplication.ChangeRequest __ChangeRequest_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ChangeRequest> es)
            {
                return new global::LightSwitchApplication.ChangeRequest(es);
            }
            private static void __ChangeRequest_Created(global::LightSwitchApplication.ChangeRequest e)
            {
                e.ChangeRequest_Created();
            }
            private static bool __ChangeRequest_AllowSaveWithErrors(global::LightSwitchApplication.ChangeRequest e)
            {
                bool result = false;
                e.ChangeRequest_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, string> Reference
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.Reference) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, string> ChangeRequestTitle
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.ChangeRequestTitle) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, string> ChangeRequestDescription
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.ChangeRequestDescription) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::System.DateTime> DateRaised
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.DateRaised) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::System.DateTime> TargetClosureDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.TargetClosureDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::System.Nullable<global::System.DateTime>> DateClosed
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.DateClosed) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::LightSwitchApplication.Employee> RaisedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.RaisedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::LightSwitchApplication.Employee>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::LightSwitchApplication.ChangeRequestStatus> ChangeRequestStatus
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.ChangeRequestStatus) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::LightSwitchApplication.ChangeRequestStatus>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::LightSwitchApplication.DocumentVersion> DocumentVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.DocumentVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::LightSwitchApplication.DocumentVersion>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string Reference { get; set; }
                new string ChangeRequestTitle { get; set; }
                new string ChangeRequestDescription { get; set; }
                new global::System.DateTime DateRaised { get; set; }
                new global::System.DateTime TargetClosureDate { get; set; }
                new global::System.Nullable<global::System.DateTime> DateClosed { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation RaisedBy { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation ChangeRequestStatus { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation DocumentVersion { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ChangeRequest.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, int>.Data> c, global::LightSwitchApplication.ChangeRequest.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.ChangeRequest e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.ChangeRequest e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.ChangeRequest e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, string>.Entry
                    Reference = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, string>.Entry(
                        "Reference",
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._Reference_Stub,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._Reference_ComputeIsReadOnly,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._Reference_Validate,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._Reference_GetImplementationValue,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._Reference_SetImplementationValue,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._Reference_OnValueChanged);
                private static void _Reference_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ChangeRequest.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, string>.Data> c, global::LightSwitchApplication.ChangeRequest.DetailsClass d, object sf)
                {
                    c(d, ref d._Reference, sf);
                }
                private static bool _Reference_ComputeIsReadOnly(global::LightSwitchApplication.ChangeRequest e)
                {
                    bool result = false;
                    e.Reference_IsReadOnly(ref result);
                    return result;
                }
                private static void _Reference_Validate(global::LightSwitchApplication.ChangeRequest e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Reference_Validate(r);
                }
                private static string _Reference_GetImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass d)
                {
                    return d.ImplementationEntity.Reference;
                }
                private static void _Reference_SetImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Reference = v;
                }
                private static void _Reference_OnValueChanged(global::LightSwitchApplication.ChangeRequest e)
                {
                    e.Reference_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, string>.Entry
                    ChangeRequestTitle = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, string>.Entry(
                        "ChangeRequestTitle",
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._ChangeRequestTitle_Stub,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._ChangeRequestTitle_ComputeIsReadOnly,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._ChangeRequestTitle_Validate,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._ChangeRequestTitle_GetImplementationValue,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._ChangeRequestTitle_SetImplementationValue,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._ChangeRequestTitle_OnValueChanged);
                private static void _ChangeRequestTitle_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ChangeRequest.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, string>.Data> c, global::LightSwitchApplication.ChangeRequest.DetailsClass d, object sf)
                {
                    c(d, ref d._ChangeRequestTitle, sf);
                }
                private static bool _ChangeRequestTitle_ComputeIsReadOnly(global::LightSwitchApplication.ChangeRequest e)
                {
                    bool result = false;
                    e.ChangeRequestTitle_IsReadOnly(ref result);
                    return result;
                }
                private static void _ChangeRequestTitle_Validate(global::LightSwitchApplication.ChangeRequest e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ChangeRequestTitle_Validate(r);
                }
                private static string _ChangeRequestTitle_GetImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass d)
                {
                    return d.ImplementationEntity.ChangeRequestTitle;
                }
                private static void _ChangeRequestTitle_SetImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ChangeRequestTitle = v;
                }
                private static void _ChangeRequestTitle_OnValueChanged(global::LightSwitchApplication.ChangeRequest e)
                {
                    e.ChangeRequestTitle_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, string>.Entry
                    ChangeRequestDescription = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, string>.Entry(
                        "ChangeRequestDescription",
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._ChangeRequestDescription_Stub,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._ChangeRequestDescription_ComputeIsReadOnly,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._ChangeRequestDescription_Validate,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._ChangeRequestDescription_GetImplementationValue,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._ChangeRequestDescription_SetImplementationValue,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._ChangeRequestDescription_OnValueChanged);
                private static void _ChangeRequestDescription_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ChangeRequest.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, string>.Data> c, global::LightSwitchApplication.ChangeRequest.DetailsClass d, object sf)
                {
                    c(d, ref d._ChangeRequestDescription, sf);
                }
                private static bool _ChangeRequestDescription_ComputeIsReadOnly(global::LightSwitchApplication.ChangeRequest e)
                {
                    bool result = false;
                    e.ChangeRequestDescription_IsReadOnly(ref result);
                    return result;
                }
                private static void _ChangeRequestDescription_Validate(global::LightSwitchApplication.ChangeRequest e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ChangeRequestDescription_Validate(r);
                }
                private static string _ChangeRequestDescription_GetImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass d)
                {
                    return d.ImplementationEntity.ChangeRequestDescription;
                }
                private static void _ChangeRequestDescription_SetImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ChangeRequestDescription = v;
                }
                private static void _ChangeRequestDescription_OnValueChanged(global::LightSwitchApplication.ChangeRequest e)
                {
                    e.ChangeRequestDescription_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::System.DateTime>.Entry
                    DateRaised = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::System.DateTime>.Entry(
                        "DateRaised",
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._DateRaised_Stub,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._DateRaised_ComputeIsReadOnly,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._DateRaised_Validate,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._DateRaised_GetImplementationValue,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._DateRaised_SetImplementationValue,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._DateRaised_OnValueChanged);
                private static void _DateRaised_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ChangeRequest.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.ChangeRequest.DetailsClass d, object sf)
                {
                    c(d, ref d._DateRaised, sf);
                }
                private static bool _DateRaised_ComputeIsReadOnly(global::LightSwitchApplication.ChangeRequest e)
                {
                    bool result = false;
                    e.DateRaised_IsReadOnly(ref result);
                    return result;
                }
                private static void _DateRaised_Validate(global::LightSwitchApplication.ChangeRequest e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DateRaised_Validate(r);
                }
                private static global::System.DateTime _DateRaised_GetImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass d)
                {
                    return d.ImplementationEntity.DateRaised;
                }
                private static void _DateRaised_SetImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.DateRaised = global::LightSwitchApplication.ChangeRequest.DetailsClass.TruncateDate(v);
                }
                private static void _DateRaised_OnValueChanged(global::LightSwitchApplication.ChangeRequest e)
                {
                    e.DateRaised_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::System.DateTime>.Entry
                    TargetClosureDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::System.DateTime>.Entry(
                        "TargetClosureDate",
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._TargetClosureDate_Stub,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._TargetClosureDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._TargetClosureDate_Validate,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._TargetClosureDate_GetImplementationValue,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._TargetClosureDate_SetImplementationValue,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._TargetClosureDate_OnValueChanged);
                private static void _TargetClosureDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ChangeRequest.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.ChangeRequest.DetailsClass d, object sf)
                {
                    c(d, ref d._TargetClosureDate, sf);
                }
                private static bool _TargetClosureDate_ComputeIsReadOnly(global::LightSwitchApplication.ChangeRequest e)
                {
                    bool result = false;
                    e.TargetClosureDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _TargetClosureDate_Validate(global::LightSwitchApplication.ChangeRequest e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.TargetClosureDate_Validate(r);
                }
                private static global::System.DateTime _TargetClosureDate_GetImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass d)
                {
                    return d.ImplementationEntity.TargetClosureDate;
                }
                private static void _TargetClosureDate_SetImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.TargetClosureDate = global::LightSwitchApplication.ChangeRequest.DetailsClass.TruncateDate(v);
                }
                private static void _TargetClosureDate_OnValueChanged(global::LightSwitchApplication.ChangeRequest e)
                {
                    e.TargetClosureDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    DateClosed = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "DateClosed",
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._DateClosed_Stub,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._DateClosed_ComputeIsReadOnly,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._DateClosed_Validate,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._DateClosed_GetImplementationValue,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._DateClosed_SetImplementationValue,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._DateClosed_OnValueChanged);
                private static void _DateClosed_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ChangeRequest.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.ChangeRequest.DetailsClass d, object sf)
                {
                    c(d, ref d._DateClosed, sf);
                }
                private static bool _DateClosed_ComputeIsReadOnly(global::LightSwitchApplication.ChangeRequest e)
                {
                    bool result = false;
                    e.DateClosed_IsReadOnly(ref result);
                    return result;
                }
                private static void _DateClosed_Validate(global::LightSwitchApplication.ChangeRequest e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DateClosed_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _DateClosed_GetImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass d)
                {
                    return d.ImplementationEntity.DateClosed;
                }
                private static void _DateClosed_SetImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.DateClosed = global::LightSwitchApplication.ChangeRequest.DetailsClass.TruncateDate(v);
                }
                private static void _DateClosed_OnValueChanged(global::LightSwitchApplication.ChangeRequest e)
                {
                    e.DateClosed_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ChangeRequest.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, string>.Data> c, global::LightSwitchApplication.ChangeRequest.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.ChangeRequest e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.ChangeRequest e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.ChangeRequest e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ChangeRequest.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.ChangeRequest.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.ChangeRequest e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.ChangeRequest e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.ChangeRequest e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ChangeRequest.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, string>.Data> c, global::LightSwitchApplication.ChangeRequest.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.ChangeRequest e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.ChangeRequest e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.ChangeRequest e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ChangeRequest.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.ChangeRequest.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.ChangeRequest e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.ChangeRequest e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.ChangeRequest e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ChangeRequest.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.ChangeRequest.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.ChangeRequest e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.ChangeRequest e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.ChangeRequest e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::LightSwitchApplication.Employee>.Entry
                    RaisedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::LightSwitchApplication.Employee>.Entry(
                        "RaisedBy",
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._RaisedBy_Stub,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._RaisedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._RaisedBy_Validate,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._RaisedBy_GetCoreImplementationValue,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._RaisedBy_GetImplementationValue,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._RaisedBy_SetImplementationValue,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._RaisedBy_Refresh,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._RaisedBy_OnValueChanged);
                private static void _RaisedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ChangeRequest.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::LightSwitchApplication.Employee>.Data> c, global::LightSwitchApplication.ChangeRequest.DetailsClass d, object sf)
                {
                    c(d, ref d._RaisedBy, sf);
                }
                private static bool _RaisedBy_ComputeIsReadOnly(global::LightSwitchApplication.ChangeRequest e)
                {
                    bool result = false;
                    e.RaisedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _RaisedBy_Validate(global::LightSwitchApplication.ChangeRequest e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RaisedBy_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _RaisedBy_GetCoreImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass d)
                {
                    return d.ImplementationEntity.RaisedBy;
                }
                private static global::LightSwitchApplication.Employee _RaisedBy_GetImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Employee, global::LightSwitchApplication.Employee.DetailsClass>(global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.RaisedBy, ref d._RaisedBy);
                }
                private static void _RaisedBy_SetImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass d, global::LightSwitchApplication.Employee v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.RaisedBy, ref d._RaisedBy, (i, ev) => i.RaisedBy = ev, v);
                }
                private static void _RaisedBy_Refresh(global::LightSwitchApplication.ChangeRequest.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.RaisedBy, ref d._RaisedBy);
                }
                private static void _RaisedBy_OnValueChanged(global::LightSwitchApplication.ChangeRequest e)
                {
                    e.RaisedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::LightSwitchApplication.ChangeRequestStatus>.Entry
                    ChangeRequestStatus = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::LightSwitchApplication.ChangeRequestStatus>.Entry(
                        "ChangeRequestStatus",
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._ChangeRequestStatus_Stub,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._ChangeRequestStatus_ComputeIsReadOnly,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._ChangeRequestStatus_Validate,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._ChangeRequestStatus_GetCoreImplementationValue,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._ChangeRequestStatus_GetImplementationValue,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._ChangeRequestStatus_SetImplementationValue,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._ChangeRequestStatus_Refresh,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._ChangeRequestStatus_OnValueChanged);
                private static void _ChangeRequestStatus_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ChangeRequest.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::LightSwitchApplication.ChangeRequestStatus>.Data> c, global::LightSwitchApplication.ChangeRequest.DetailsClass d, object sf)
                {
                    c(d, ref d._ChangeRequestStatus, sf);
                }
                private static bool _ChangeRequestStatus_ComputeIsReadOnly(global::LightSwitchApplication.ChangeRequest e)
                {
                    bool result = false;
                    e.ChangeRequestStatus_IsReadOnly(ref result);
                    return result;
                }
                private static void _ChangeRequestStatus_Validate(global::LightSwitchApplication.ChangeRequest e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ChangeRequestStatus_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _ChangeRequestStatus_GetCoreImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass d)
                {
                    return d.ImplementationEntity.ChangeRequestStatus;
                }
                private static global::LightSwitchApplication.ChangeRequestStatus _ChangeRequestStatus_GetImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.ChangeRequestStatus, global::LightSwitchApplication.ChangeRequestStatus.DetailsClass>(global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.ChangeRequestStatus, ref d._ChangeRequestStatus);
                }
                private static void _ChangeRequestStatus_SetImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass d, global::LightSwitchApplication.ChangeRequestStatus v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.ChangeRequestStatus, ref d._ChangeRequestStatus, (i, ev) => i.ChangeRequestStatus = ev, v);
                }
                private static void _ChangeRequestStatus_Refresh(global::LightSwitchApplication.ChangeRequest.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.ChangeRequestStatus, ref d._ChangeRequestStatus);
                }
                private static void _ChangeRequestStatus_OnValueChanged(global::LightSwitchApplication.ChangeRequest e)
                {
                    e.ChangeRequestStatus_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::LightSwitchApplication.DocumentVersion>.Entry
                    DocumentVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::LightSwitchApplication.DocumentVersion>.Entry(
                        "DocumentVersion",
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._DocumentVersion_Stub,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._DocumentVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._DocumentVersion_Validate,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._DocumentVersion_GetCoreImplementationValue,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._DocumentVersion_GetImplementationValue,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._DocumentVersion_SetImplementationValue,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._DocumentVersion_Refresh,
                        global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties._DocumentVersion_OnValueChanged);
                private static void _DocumentVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ChangeRequest.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::LightSwitchApplication.DocumentVersion>.Data> c, global::LightSwitchApplication.ChangeRequest.DetailsClass d, object sf)
                {
                    c(d, ref d._DocumentVersion, sf);
                }
                private static bool _DocumentVersion_ComputeIsReadOnly(global::LightSwitchApplication.ChangeRequest e)
                {
                    bool result = false;
                    e.DocumentVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _DocumentVersion_Validate(global::LightSwitchApplication.ChangeRequest e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DocumentVersion_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _DocumentVersion_GetCoreImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass d)
                {
                    return d.ImplementationEntity.DocumentVersion;
                }
                private static global::LightSwitchApplication.DocumentVersion _DocumentVersion_GetImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.DocumentVersion, global::LightSwitchApplication.DocumentVersion.DetailsClass>(global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.DocumentVersion, ref d._DocumentVersion);
                }
                private static void _DocumentVersion_SetImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass d, global::LightSwitchApplication.DocumentVersion v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.DocumentVersion, ref d._DocumentVersion, (i, ev) => i.DocumentVersion = ev, v);
                }
                private static void _DocumentVersion_Refresh(global::LightSwitchApplication.ChangeRequest.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.ChangeRequest.DetailsClass.PropertySetProperties.DocumentVersion, ref d._DocumentVersion);
                }
                private static void _DocumentVersion_OnValueChanged(global::LightSwitchApplication.ChangeRequest e)
                {
                    e.DocumentVersion_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, string>.Data _Reference;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, string>.Data _ChangeRequestTitle;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, string>.Data _ChangeRequestDescription;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::System.DateTime>.Data _DateRaised;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::System.DateTime>.Data _TargetClosureDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _DateClosed;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::LightSwitchApplication.Employee>.Data _RaisedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::LightSwitchApplication.ChangeRequestStatus>.Data _ChangeRequestStatus;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ChangeRequest, global::LightSwitchApplication.ChangeRequest.DetailsClass, global::LightSwitchApplication.DocumentVersion>.Data _DocumentVersion;
            
        }
    
        #endregion
    }
    
    #endregion
}
