

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class Document : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Document entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Document()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Document(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Document> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Document.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Document_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Document_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Document.DetailsClass.GetValue(this, global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Document.DetailsClass.SetValue(this, global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string DocumentTitle
        {
            get
            {
                return global::LightSwitchApplication.Document.DetailsClass.GetValue(this, global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.DocumentTitle);
            }
            set
            {
                global::LightSwitchApplication.Document.DetailsClass.SetValue(this, global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.DocumentTitle, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DocumentTitle_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DocumentTitle_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DocumentTitle_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Reference
        {
            get
            {
                return global::LightSwitchApplication.Document.DetailsClass.GetValue(this, global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.Reference);
            }
            set
            {
                global::LightSwitchApplication.Document.DetailsClass.SetValue(this, global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.Reference, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Reference_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Reference_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Reference_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool InUse
        {
            get
            {
                return global::LightSwitchApplication.Document.DetailsClass.GetValue(this, global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.InUse);
            }
            set
            {
                global::LightSwitchApplication.Document.DetailsClass.SetValue(this, global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.InUse, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InUse_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InUse_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InUse_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.Document.DetailsClass.GetValue(this, global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.Document.DetailsClass.GetValue(this, global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.Document.DetailsClass.GetValue(this, global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.Document.DetailsClass.GetValue(this, global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.Document.DetailsClass.GetValue(this, global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.Document.DetailsClass.SetValue(this, global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.DocumentType DocumentType
        {
            get
            {
                return global::LightSwitchApplication.Document.DetailsClass.GetValue(this, global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.DocumentType);
            }
            set
            {
                global::LightSwitchApplication.Document.DetailsClass.SetValue(this, global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.DocumentType, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DocumentType_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DocumentType_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DocumentType_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Employee DocumentOwner
        {
            get
            {
                return global::LightSwitchApplication.Document.DetailsClass.GetValue(this, global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.DocumentOwner);
            }
            set
            {
                global::LightSwitchApplication.Document.DetailsClass.SetValue(this, global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.DocumentOwner, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DocumentOwner_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DocumentOwner_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DocumentOwner_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.DocumentVersion> DocumentVersions
        {
            get
            {
                return global::LightSwitchApplication.Document.DetailsClass.GetValue(this, global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.DocumentVersions);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.DocumentVersion> DocumentVersionsQuery
        {
            get
            {
                return global::LightSwitchApplication.Document.DetailsClass.GetQuery(this, global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.DocumentVersions);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Document,
                global::LightSwitchApplication.Document.DetailsClass,
                global::LightSwitchApplication.Document.DetailsClass.IImplementation,
                global::LightSwitchApplication.Document.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass>.Entry
                __DocumentEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass>.Entry(
                    global::LightSwitchApplication.Document.DetailsClass.__Document_CreateNew,
                    global::LightSwitchApplication.Document.DetailsClass.__Document_Created,
                    global::LightSwitchApplication.Document.DetailsClass.__Document_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Document __Document_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Document> es)
            {
                return new global::LightSwitchApplication.Document(es);
            }
            private static void __Document_Created(global::LightSwitchApplication.Document e)
            {
                e.Document_Created();
            }
            private static bool __Document_AllowSaveWithErrors(global::LightSwitchApplication.Document e)
            {
                bool result = false;
                e.Document_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Document.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, string> DocumentTitle
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.DocumentTitle) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, string> Reference
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.Reference) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, bool> InUse
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.InUse) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, bool>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, global::LightSwitchApplication.DocumentType> DocumentType
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.DocumentType) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, global::LightSwitchApplication.DocumentType>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, global::LightSwitchApplication.Employee> DocumentOwner
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.DocumentOwner) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, global::LightSwitchApplication.Employee>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, global::LightSwitchApplication.DocumentVersion> DocumentVersions
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.DocumentVersions) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, global::LightSwitchApplication.DocumentVersion>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string DocumentTitle { get; set; }
                new string Reference { get; set; }
                new bool InUse { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation DocumentType { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation DocumentOwner { get; set; }
                new global::System.Collections.IEnumerable DocumentVersions { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Document.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, int>.Data> c, global::LightSwitchApplication.Document.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Document e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Document e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Document.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Document.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Document e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, string>.Entry
                    DocumentTitle = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, string>.Entry(
                        "DocumentTitle",
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._DocumentTitle_Stub,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._DocumentTitle_ComputeIsReadOnly,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._DocumentTitle_Validate,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._DocumentTitle_GetImplementationValue,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._DocumentTitle_SetImplementationValue,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._DocumentTitle_OnValueChanged);
                private static void _DocumentTitle_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Document.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, string>.Data> c, global::LightSwitchApplication.Document.DetailsClass d, object sf)
                {
                    c(d, ref d._DocumentTitle, sf);
                }
                private static bool _DocumentTitle_ComputeIsReadOnly(global::LightSwitchApplication.Document e)
                {
                    bool result = false;
                    e.DocumentTitle_IsReadOnly(ref result);
                    return result;
                }
                private static void _DocumentTitle_Validate(global::LightSwitchApplication.Document e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DocumentTitle_Validate(r);
                }
                private static string _DocumentTitle_GetImplementationValue(global::LightSwitchApplication.Document.DetailsClass d)
                {
                    return d.ImplementationEntity.DocumentTitle;
                }
                private static void _DocumentTitle_SetImplementationValue(global::LightSwitchApplication.Document.DetailsClass d, string v)
                {
                    d.ImplementationEntity.DocumentTitle = v;
                }
                private static void _DocumentTitle_OnValueChanged(global::LightSwitchApplication.Document e)
                {
                    e.DocumentTitle_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, string>.Entry
                    Reference = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, string>.Entry(
                        "Reference",
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._Reference_Stub,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._Reference_ComputeIsReadOnly,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._Reference_Validate,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._Reference_GetImplementationValue,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._Reference_SetImplementationValue,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._Reference_OnValueChanged);
                private static void _Reference_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Document.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, string>.Data> c, global::LightSwitchApplication.Document.DetailsClass d, object sf)
                {
                    c(d, ref d._Reference, sf);
                }
                private static bool _Reference_ComputeIsReadOnly(global::LightSwitchApplication.Document e)
                {
                    bool result = false;
                    e.Reference_IsReadOnly(ref result);
                    return result;
                }
                private static void _Reference_Validate(global::LightSwitchApplication.Document e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Reference_Validate(r);
                }
                private static string _Reference_GetImplementationValue(global::LightSwitchApplication.Document.DetailsClass d)
                {
                    return d.ImplementationEntity.Reference;
                }
                private static void _Reference_SetImplementationValue(global::LightSwitchApplication.Document.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Reference = v;
                }
                private static void _Reference_OnValueChanged(global::LightSwitchApplication.Document e)
                {
                    e.Reference_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, bool>.Entry
                    InUse = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, bool>.Entry(
                        "InUse",
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._InUse_Stub,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._InUse_ComputeIsReadOnly,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._InUse_Validate,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._InUse_GetImplementationValue,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._InUse_SetImplementationValue,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._InUse_OnValueChanged);
                private static void _InUse_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Document.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, bool>.Data> c, global::LightSwitchApplication.Document.DetailsClass d, object sf)
                {
                    c(d, ref d._InUse, sf);
                }
                private static bool _InUse_ComputeIsReadOnly(global::LightSwitchApplication.Document e)
                {
                    bool result = false;
                    e.InUse_IsReadOnly(ref result);
                    return result;
                }
                private static void _InUse_Validate(global::LightSwitchApplication.Document e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.InUse_Validate(r);
                }
                private static bool _InUse_GetImplementationValue(global::LightSwitchApplication.Document.DetailsClass d)
                {
                    return d.ImplementationEntity.InUse;
                }
                private static void _InUse_SetImplementationValue(global::LightSwitchApplication.Document.DetailsClass d, bool v)
                {
                    d.ImplementationEntity.InUse = v;
                }
                private static void _InUse_OnValueChanged(global::LightSwitchApplication.Document e)
                {
                    e.InUse_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Document.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, string>.Data> c, global::LightSwitchApplication.Document.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.Document e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.Document e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.Document.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.Document e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Document.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.Document.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.Document e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.Document e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.Document.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.Document e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Document.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, string>.Data> c, global::LightSwitchApplication.Document.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.Document e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.Document e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.Document.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.Document e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Document.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.Document.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.Document e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.Document e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.Document.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.Document e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Document.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Document.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.Document e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.Document e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.Document.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.Document.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.Document e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, global::LightSwitchApplication.DocumentType>.Entry
                    DocumentType = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, global::LightSwitchApplication.DocumentType>.Entry(
                        "DocumentType",
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._DocumentType_Stub,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._DocumentType_ComputeIsReadOnly,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._DocumentType_Validate,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._DocumentType_GetCoreImplementationValue,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._DocumentType_GetImplementationValue,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._DocumentType_SetImplementationValue,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._DocumentType_Refresh,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._DocumentType_OnValueChanged);
                private static void _DocumentType_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Document.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, global::LightSwitchApplication.DocumentType>.Data> c, global::LightSwitchApplication.Document.DetailsClass d, object sf)
                {
                    c(d, ref d._DocumentType, sf);
                }
                private static bool _DocumentType_ComputeIsReadOnly(global::LightSwitchApplication.Document e)
                {
                    bool result = false;
                    e.DocumentType_IsReadOnly(ref result);
                    return result;
                }
                private static void _DocumentType_Validate(global::LightSwitchApplication.Document e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DocumentType_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _DocumentType_GetCoreImplementationValue(global::LightSwitchApplication.Document.DetailsClass d)
                {
                    return d.ImplementationEntity.DocumentType;
                }
                private static global::LightSwitchApplication.DocumentType _DocumentType_GetImplementationValue(global::LightSwitchApplication.Document.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.DocumentType, global::LightSwitchApplication.DocumentType.DetailsClass>(global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.DocumentType, ref d._DocumentType);
                }
                private static void _DocumentType_SetImplementationValue(global::LightSwitchApplication.Document.DetailsClass d, global::LightSwitchApplication.DocumentType v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.DocumentType, ref d._DocumentType, (i, ev) => i.DocumentType = ev, v);
                }
                private static void _DocumentType_Refresh(global::LightSwitchApplication.Document.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.DocumentType, ref d._DocumentType);
                }
                private static void _DocumentType_OnValueChanged(global::LightSwitchApplication.Document e)
                {
                    e.DocumentType_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, global::LightSwitchApplication.Employee>.Entry
                    DocumentOwner = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, global::LightSwitchApplication.Employee>.Entry(
                        "DocumentOwner",
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._DocumentOwner_Stub,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._DocumentOwner_ComputeIsReadOnly,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._DocumentOwner_Validate,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._DocumentOwner_GetCoreImplementationValue,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._DocumentOwner_GetImplementationValue,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._DocumentOwner_SetImplementationValue,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._DocumentOwner_Refresh,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._DocumentOwner_OnValueChanged);
                private static void _DocumentOwner_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Document.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, global::LightSwitchApplication.Employee>.Data> c, global::LightSwitchApplication.Document.DetailsClass d, object sf)
                {
                    c(d, ref d._DocumentOwner, sf);
                }
                private static bool _DocumentOwner_ComputeIsReadOnly(global::LightSwitchApplication.Document e)
                {
                    bool result = false;
                    e.DocumentOwner_IsReadOnly(ref result);
                    return result;
                }
                private static void _DocumentOwner_Validate(global::LightSwitchApplication.Document e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DocumentOwner_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _DocumentOwner_GetCoreImplementationValue(global::LightSwitchApplication.Document.DetailsClass d)
                {
                    return d.ImplementationEntity.DocumentOwner;
                }
                private static global::LightSwitchApplication.Employee _DocumentOwner_GetImplementationValue(global::LightSwitchApplication.Document.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Employee, global::LightSwitchApplication.Employee.DetailsClass>(global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.DocumentOwner, ref d._DocumentOwner);
                }
                private static void _DocumentOwner_SetImplementationValue(global::LightSwitchApplication.Document.DetailsClass d, global::LightSwitchApplication.Employee v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.DocumentOwner, ref d._DocumentOwner, (i, ev) => i.DocumentOwner = ev, v);
                }
                private static void _DocumentOwner_Refresh(global::LightSwitchApplication.Document.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.DocumentOwner, ref d._DocumentOwner);
                }
                private static void _DocumentOwner_OnValueChanged(global::LightSwitchApplication.Document e)
                {
                    e.DocumentOwner_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, global::LightSwitchApplication.DocumentVersion>.Entry
                    DocumentVersions = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, global::LightSwitchApplication.DocumentVersion>.Entry(
                        "DocumentVersions",
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._DocumentVersions_Stub,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._DocumentVersions_GetReferencedEntities,
                        global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties._DocumentVersions_GetEntityCollection);
                private static void _DocumentVersions_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Document.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, global::LightSwitchApplication.DocumentVersion>.Data> c, global::LightSwitchApplication.Document.DetailsClass d, object sf)
                {
                    c(d, ref d._DocumentVersions, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.DocumentVersion> _DocumentVersions_GetReferencedEntities(global::LightSwitchApplication.Document.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.DocumentVersion, global::LightSwitchApplication.DocumentVersion.DetailsClass>(global::LightSwitchApplication.Document.DetailsClass.PropertySetProperties.DocumentVersions, ref d._DocumentVersions);
                }
                private static global::System.Collections.IEnumerable _DocumentVersions_GetEntityCollection(global::LightSwitchApplication.Document.DetailsClass d)
                {
                    return d.ImplementationEntity.DocumentVersions;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, string>.Data _DocumentTitle;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, string>.Data _Reference;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, bool>.Data _InUse;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, global::LightSwitchApplication.DocumentType>.Data _DocumentType;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, global::LightSwitchApplication.Employee>.Data _DocumentOwner;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Document, global::LightSwitchApplication.Document.DetailsClass, global::LightSwitchApplication.DocumentVersion>.Data _DocumentVersions;
            
        }
    
        #endregion
    }
    
    #endregion
}
