

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class DocumentVersionReview : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the DocumentVersionReview entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DocumentVersionReview()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DocumentVersionReview(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.DocumentVersionReview> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.DocumentVersionReview.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DocumentVersionReview_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DocumentVersionReview_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.DocumentVersionReview.DetailsClass.GetValue(this, global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.DocumentVersionReview.DetailsClass.SetValue(this, global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime DateDue
        {
            get
            {
                return global::LightSwitchApplication.DocumentVersionReview.DetailsClass.GetValue(this, global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties.DateDue);
            }
            set
            {
                global::LightSwitchApplication.DocumentVersionReview.DetailsClass.SetValue(this, global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties.DateDue, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateDue_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateDue_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateDue_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> DateCompleted
        {
            get
            {
                return global::LightSwitchApplication.DocumentVersionReview.DetailsClass.GetValue(this, global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties.DateCompleted);
            }
            set
            {
                global::LightSwitchApplication.DocumentVersionReview.DetailsClass.SetValue(this, global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties.DateCompleted, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateCompleted_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateCompleted_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateCompleted_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Outcome
        {
            get
            {
                return global::LightSwitchApplication.DocumentVersionReview.DetailsClass.GetValue(this, global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties.Outcome);
            }
            set
            {
                global::LightSwitchApplication.DocumentVersionReview.DetailsClass.SetValue(this, global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties.Outcome, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Outcome_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Outcome_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Outcome_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.DocumentVersionReview.DetailsClass.GetValue(this, global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.DocumentVersionReview.DetailsClass.GetValue(this, global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.DocumentVersionReview.DetailsClass.GetValue(this, global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.DocumentVersionReview.DetailsClass.GetValue(this, global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.DocumentVersionReview.DetailsClass.GetValue(this, global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.DocumentVersionReview.DetailsClass.SetValue(this, global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.DocumentVersionHolder DocumentVersionHolder
        {
            get
            {
                return global::LightSwitchApplication.DocumentVersionReview.DetailsClass.GetValue(this, global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties.DocumentVersionHolder);
            }
            set
            {
                global::LightSwitchApplication.DocumentVersionReview.DetailsClass.SetValue(this, global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties.DocumentVersionHolder, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DocumentVersionHolder_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DocumentVersionHolder_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DocumentVersionHolder_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.DocumentVersionReview,
                global::LightSwitchApplication.DocumentVersionReview.DetailsClass,
                global::LightSwitchApplication.DocumentVersionReview.DetailsClass.IImplementation,
                global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass>.Entry
                __DocumentVersionReviewEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass>.Entry(
                    global::LightSwitchApplication.DocumentVersionReview.DetailsClass.__DocumentVersionReview_CreateNew,
                    global::LightSwitchApplication.DocumentVersionReview.DetailsClass.__DocumentVersionReview_Created,
                    global::LightSwitchApplication.DocumentVersionReview.DetailsClass.__DocumentVersionReview_AllowSaveWithErrors);
            private static global::LightSwitchApplication.DocumentVersionReview __DocumentVersionReview_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.DocumentVersionReview> es)
            {
                return new global::LightSwitchApplication.DocumentVersionReview(es);
            }
            private static void __DocumentVersionReview_Created(global::LightSwitchApplication.DocumentVersionReview e)
            {
                e.DocumentVersionReview_Created();
            }
            private static bool __DocumentVersionReview_AllowSaveWithErrors(global::LightSwitchApplication.DocumentVersionReview e)
            {
                bool result = false;
                e.DocumentVersionReview_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::System.DateTime> DateDue
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties.DateDue) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::System.Nullable<global::System.DateTime>> DateCompleted
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties.DateCompleted) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, string> Outcome
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties.Outcome) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::LightSwitchApplication.DocumentVersionHolder> DocumentVersionHolder
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties.DocumentVersionHolder) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::LightSwitchApplication.DocumentVersionHolder>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new global::System.DateTime DateDue { get; set; }
                new global::System.Nullable<global::System.DateTime> DateCompleted { get; set; }
                new string Outcome { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation DocumentVersionHolder { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, int>.Data> c, global::LightSwitchApplication.DocumentVersionReview.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.DocumentVersionReview e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.DocumentVersionReview e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.DocumentVersionReview.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.DocumentVersionReview.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.DocumentVersionReview e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::System.DateTime>.Entry
                    DateDue = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::System.DateTime>.Entry(
                        "DateDue",
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._DateDue_Stub,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._DateDue_ComputeIsReadOnly,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._DateDue_Validate,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._DateDue_GetImplementationValue,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._DateDue_SetImplementationValue,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._DateDue_OnValueChanged);
                private static void _DateDue_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.DocumentVersionReview.DetailsClass d, object sf)
                {
                    c(d, ref d._DateDue, sf);
                }
                private static bool _DateDue_ComputeIsReadOnly(global::LightSwitchApplication.DocumentVersionReview e)
                {
                    bool result = false;
                    e.DateDue_IsReadOnly(ref result);
                    return result;
                }
                private static void _DateDue_Validate(global::LightSwitchApplication.DocumentVersionReview e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DateDue_Validate(r);
                }
                private static global::System.DateTime _DateDue_GetImplementationValue(global::LightSwitchApplication.DocumentVersionReview.DetailsClass d)
                {
                    return d.ImplementationEntity.DateDue;
                }
                private static void _DateDue_SetImplementationValue(global::LightSwitchApplication.DocumentVersionReview.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.DateDue = global::LightSwitchApplication.DocumentVersionReview.DetailsClass.TruncateDate(v);
                }
                private static void _DateDue_OnValueChanged(global::LightSwitchApplication.DocumentVersionReview e)
                {
                    e.DateDue_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    DateCompleted = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "DateCompleted",
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._DateCompleted_Stub,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._DateCompleted_ComputeIsReadOnly,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._DateCompleted_Validate,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._DateCompleted_GetImplementationValue,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._DateCompleted_SetImplementationValue,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._DateCompleted_OnValueChanged);
                private static void _DateCompleted_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.DocumentVersionReview.DetailsClass d, object sf)
                {
                    c(d, ref d._DateCompleted, sf);
                }
                private static bool _DateCompleted_ComputeIsReadOnly(global::LightSwitchApplication.DocumentVersionReview e)
                {
                    bool result = false;
                    e.DateCompleted_IsReadOnly(ref result);
                    return result;
                }
                private static void _DateCompleted_Validate(global::LightSwitchApplication.DocumentVersionReview e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DateCompleted_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _DateCompleted_GetImplementationValue(global::LightSwitchApplication.DocumentVersionReview.DetailsClass d)
                {
                    return d.ImplementationEntity.DateCompleted;
                }
                private static void _DateCompleted_SetImplementationValue(global::LightSwitchApplication.DocumentVersionReview.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.DateCompleted = global::LightSwitchApplication.DocumentVersionReview.DetailsClass.TruncateDate(v);
                }
                private static void _DateCompleted_OnValueChanged(global::LightSwitchApplication.DocumentVersionReview e)
                {
                    e.DateCompleted_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, string>.Entry
                    Outcome = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, string>.Entry(
                        "Outcome",
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._Outcome_Stub,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._Outcome_ComputeIsReadOnly,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._Outcome_Validate,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._Outcome_GetImplementationValue,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._Outcome_SetImplementationValue,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._Outcome_OnValueChanged);
                private static void _Outcome_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, string>.Data> c, global::LightSwitchApplication.DocumentVersionReview.DetailsClass d, object sf)
                {
                    c(d, ref d._Outcome, sf);
                }
                private static bool _Outcome_ComputeIsReadOnly(global::LightSwitchApplication.DocumentVersionReview e)
                {
                    bool result = false;
                    e.Outcome_IsReadOnly(ref result);
                    return result;
                }
                private static void _Outcome_Validate(global::LightSwitchApplication.DocumentVersionReview e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Outcome_Validate(r);
                }
                private static string _Outcome_GetImplementationValue(global::LightSwitchApplication.DocumentVersionReview.DetailsClass d)
                {
                    return d.ImplementationEntity.Outcome;
                }
                private static void _Outcome_SetImplementationValue(global::LightSwitchApplication.DocumentVersionReview.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Outcome = v;
                }
                private static void _Outcome_OnValueChanged(global::LightSwitchApplication.DocumentVersionReview e)
                {
                    e.Outcome_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, string>.Data> c, global::LightSwitchApplication.DocumentVersionReview.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.DocumentVersionReview e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.DocumentVersionReview e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.DocumentVersionReview.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.DocumentVersionReview e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.DocumentVersionReview.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.DocumentVersionReview e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.DocumentVersionReview e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.DocumentVersionReview.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.DocumentVersionReview e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, string>.Data> c, global::LightSwitchApplication.DocumentVersionReview.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.DocumentVersionReview e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.DocumentVersionReview e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.DocumentVersionReview.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.DocumentVersionReview e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.DocumentVersionReview.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.DocumentVersionReview e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.DocumentVersionReview e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.DocumentVersionReview.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.DocumentVersionReview e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.DocumentVersionReview.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.DocumentVersionReview e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.DocumentVersionReview e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.DocumentVersionReview.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.DocumentVersionReview.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.DocumentVersionReview e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::LightSwitchApplication.DocumentVersionHolder>.Entry
                    DocumentVersionHolder = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::LightSwitchApplication.DocumentVersionHolder>.Entry(
                        "DocumentVersionHolder",
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._DocumentVersionHolder_Stub,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._DocumentVersionHolder_ComputeIsReadOnly,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._DocumentVersionHolder_Validate,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._DocumentVersionHolder_GetCoreImplementationValue,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._DocumentVersionHolder_GetImplementationValue,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._DocumentVersionHolder_SetImplementationValue,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._DocumentVersionHolder_Refresh,
                        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties._DocumentVersionHolder_OnValueChanged);
                private static void _DocumentVersionHolder_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::LightSwitchApplication.DocumentVersionHolder>.Data> c, global::LightSwitchApplication.DocumentVersionReview.DetailsClass d, object sf)
                {
                    c(d, ref d._DocumentVersionHolder, sf);
                }
                private static bool _DocumentVersionHolder_ComputeIsReadOnly(global::LightSwitchApplication.DocumentVersionReview e)
                {
                    bool result = false;
                    e.DocumentVersionHolder_IsReadOnly(ref result);
                    return result;
                }
                private static void _DocumentVersionHolder_Validate(global::LightSwitchApplication.DocumentVersionReview e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DocumentVersionHolder_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _DocumentVersionHolder_GetCoreImplementationValue(global::LightSwitchApplication.DocumentVersionReview.DetailsClass d)
                {
                    return d.ImplementationEntity.DocumentVersionHolder;
                }
                private static global::LightSwitchApplication.DocumentVersionHolder _DocumentVersionHolder_GetImplementationValue(global::LightSwitchApplication.DocumentVersionReview.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.DocumentVersionHolder, global::LightSwitchApplication.DocumentVersionHolder.DetailsClass>(global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties.DocumentVersionHolder, ref d._DocumentVersionHolder);
                }
                private static void _DocumentVersionHolder_SetImplementationValue(global::LightSwitchApplication.DocumentVersionReview.DetailsClass d, global::LightSwitchApplication.DocumentVersionHolder v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties.DocumentVersionHolder, ref d._DocumentVersionHolder, (i, ev) => i.DocumentVersionHolder = ev, v);
                }
                private static void _DocumentVersionHolder_Refresh(global::LightSwitchApplication.DocumentVersionReview.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.DocumentVersionReview.DetailsClass.PropertySetProperties.DocumentVersionHolder, ref d._DocumentVersionHolder);
                }
                private static void _DocumentVersionHolder_OnValueChanged(global::LightSwitchApplication.DocumentVersionReview e)
                {
                    e.DocumentVersionHolder_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::System.DateTime>.Data _DateDue;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _DateCompleted;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, string>.Data _Outcome;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DocumentVersionReview, global::LightSwitchApplication.DocumentVersionReview.DetailsClass, global::LightSwitchApplication.DocumentVersionHolder>.Data _DocumentVersionHolder;
            
        }
    
        #endregion
    }
    
    #endregion
}
