//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using global::System.Linq;

namespace LightSwitchApplication.Implementation
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationDataDataService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataService<global::LightSwitchApplication.Implementation.ApplicationData>
    {
    
        public ApplicationDataDataService() : base()
        {
        }
    
        protected override global::Microsoft.LightSwitch.IDataService GetDataService(global::Microsoft.LightSwitch.IDataWorkspace dataWorkspace)
        {
            return ((global::LightSwitchApplication.DataWorkspace)dataWorkspace).ApplicationData;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationDataServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation<global::LightSwitchApplication.Implementation.ApplicationData>
    {
        public ApplicationDataServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.Document> MyOwnedDocuments()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.Document> query;
            query = this.GetQuery<global::LightSwitchApplication.Implementation.Document>("Documents");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.DocumentVersionApproval> MyDocumentVersionApprovals()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.DocumentVersionApproval> query;
            query = global::System.Linq.Queryable.OrderByDescending(
                this.GetQuery<global::LightSwitchApplication.Implementation.DocumentVersionApproval>("DocumentVersionApprovals"),
                (d) => d.Created);
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.DocumentVersionHolder> MyHeldDocumentVersions()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.DocumentVersionHolder> query;
            query = global::System.Linq.Queryable.OrderByDescending(
                this.GetQuery<global::LightSwitchApplication.Implementation.DocumentVersionHolder>("DocumentVersionHolders"),
                (d) => d.DateDistributedTo);
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.DocumentVersionReview> MyDocumentReviews()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.DocumentVersionReview> query;
            query = global::System.Linq.Queryable.OrderByDescending(
                this.GetQuery<global::LightSwitchApplication.Implementation.DocumentVersionReview>("DocumentVersionReviews"),
                (d) => d.DateDue);
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.DocumentVersion> MyAuthoredDocumentVersions()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.DocumentVersion> query;
            query = global::System.Linq.Queryable.ThenBy(
                global::System.Linq.Queryable.ThenBy(
                    global::System.Linq.Queryable.OrderBy(
                        this.GetQuery<global::LightSwitchApplication.Implementation.DocumentVersion>("DocumentVersions"),
                        (d) => d.Document.DocumentTitle),
                    (d) => d.MajorVersionNumber),
                (d) => d.MinorVersionNumber);
            return query;
        }
    
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
            if (type == typeof(global::LightSwitchApplication.Implementation.ChangeRequest))
            {
                return new global::LightSwitchApplication.Implementation.ChangeRequest();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.ChangeRequestStatus))
            {
                return new global::LightSwitchApplication.Implementation.ChangeRequestStatus();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Document))
            {
                return new global::LightSwitchApplication.Implementation.Document();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.DocumentType))
            {
                return new global::LightSwitchApplication.Implementation.DocumentType();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.DocumentVersionApproval))
            {
                return new global::LightSwitchApplication.Implementation.DocumentVersionApproval();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.DocumentVersionHolder))
            {
                return new global::LightSwitchApplication.Implementation.DocumentVersionHolder();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.DocumentVersionReview))
            {
                return new global::LightSwitchApplication.Implementation.DocumentVersionReview();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.DocumentVersion))
            {
                return new global::LightSwitchApplication.Implementation.DocumentVersion();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Employee))
            {
                return new global::LightSwitchApplication.Implementation.Employee();
            }
    
            return base.CreateObject(type);
        }
    
        protected override global::LightSwitchApplication.Implementation.ApplicationData CreateObjectContext()
        {
            string assemblyName = global::System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
            return new global::LightSwitchApplication.Implementation.ApplicationData(this.GetEntityConnectionString(
                "_IntrinsicData",
                "res://" + assemblyName + "/ApplicationData.csdl|res://" + assemblyName + "/ApplicationData.ssdl|res://" + assemblyName + "/ApplicationData.msl",
                "System.Data.SqlClient",
                true));
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.ChangeRequest))
            {
                return new global::LightSwitchApplication.Implementation.ChangeRequest();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ChangeRequestStatus))
            {
                return new global::LightSwitchApplication.Implementation.ChangeRequestStatus();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Document))
            {
                return new global::LightSwitchApplication.Implementation.Document();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.DocumentType))
            {
                return new global::LightSwitchApplication.Implementation.DocumentType();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.DocumentVersionApproval))
            {
                return new global::LightSwitchApplication.Implementation.DocumentVersionApproval();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.DocumentVersionHolder))
            {
                return new global::LightSwitchApplication.Implementation.DocumentVersionHolder();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.DocumentVersionReview))
            {
                return new global::LightSwitchApplication.Implementation.DocumentVersionReview();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.DocumentVersion))
            {
                return new global::LightSwitchApplication.Implementation.DocumentVersion();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Employee))
            {
                return new global::LightSwitchApplication.Implementation.Employee();
            }
            return null;
        }
    
    #endregion
    
    }
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationDataService))
            {
                return new global::LightSwitchApplication.ApplicationDataService();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationDataService))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationDataServiceImplementation(dataService);
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.ChangeRequest) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ChangeRequest);
            }
            if (typeof(global::LightSwitchApplication.ChangeRequestStatus) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ChangeRequestStatus);
            }
            if (typeof(global::LightSwitchApplication.Document) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Document);
            }
            if (typeof(global::LightSwitchApplication.DocumentType) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.DocumentType);
            }
            if (typeof(global::LightSwitchApplication.DocumentVersionApproval) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.DocumentVersionApproval);
            }
            if (typeof(global::LightSwitchApplication.DocumentVersionHolder) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.DocumentVersionHolder);
            }
            if (typeof(global::LightSwitchApplication.DocumentVersionReview) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.DocumentVersionReview);
            }
            if (typeof(global::LightSwitchApplication.DocumentVersion) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.DocumentVersion);
            }
            if (typeof(global::LightSwitchApplication.Employee) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Employee);
            }
            return null;
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ChangeRequest :
        global::LightSwitchApplication.ChangeRequest.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ChangeRequest.DetailsClass.IImplementation.RaisedBy
        {
            get
            {
                return this.RaisedBy;
            }
            set
            {
                this.RaisedBy = (global::LightSwitchApplication.Implementation.Employee)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("RaisedBy");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ChangeRequest.DetailsClass.IImplementation.ChangeRequestStatus
        {
            get
            {
                return this.ChangeRequestStatus;
            }
            set
            {
                this.ChangeRequestStatus = (global::LightSwitchApplication.Implementation.ChangeRequestStatus)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ChangeRequestStatus");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ChangeRequest.DetailsClass.IImplementation.DocumentVersion
        {
            get
            {
                return this.DocumentVersion;
            }
            set
            {
                this.DocumentVersion = (global::LightSwitchApplication.Implementation.DocumentVersion)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("DocumentVersion");
                }
            }
        }
        
        partial void OnChangeRequest_EmployeeChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("RaisedBy");
            }
        }
        
        partial void OnChangeRequestStatus_ChangeRequestChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ChangeRequestStatus");
            }
        }
        
        partial void OnChangeRequest_DocumentVersionChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("DocumentVersion");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ChangeRequestStatus :
        global::LightSwitchApplication.ChangeRequestStatus.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.ChangeRequestStatus.DetailsClass.IImplementation.ChangeRequests
        {
            get
            {
                return this.ChangeRequests;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Document :
        global::LightSwitchApplication.Document.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Document.DetailsClass.IImplementation.DocumentType
        {
            get
            {
                return this.DocumentType;
            }
            set
            {
                this.DocumentType = (global::LightSwitchApplication.Implementation.DocumentType)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("DocumentType");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Document.DetailsClass.IImplementation.DocumentOwner
        {
            get
            {
                return this.DocumentOwner;
            }
            set
            {
                this.DocumentOwner = (global::LightSwitchApplication.Implementation.Employee)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("DocumentOwner");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Document.DetailsClass.IImplementation.DocumentVersions
        {
            get
            {
                return this.DocumentVersions;
            }
        }
        
        partial void OnDocumentType_DocumentChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("DocumentType");
            }
        }
        
        partial void OnDocument_EmployeeChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("DocumentOwner");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class DocumentType :
        global::LightSwitchApplication.DocumentType.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.DocumentType.DetailsClass.IImplementation.Documents
        {
            get
            {
                return this.Documents;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class DocumentVersionApproval :
        global::LightSwitchApplication.DocumentVersionApproval.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.DocumentVersionApproval.DetailsClass.IImplementation.DocumentVersion
        {
            get
            {
                return this.DocumentVersion;
            }
            set
            {
                this.DocumentVersion = (global::LightSwitchApplication.Implementation.DocumentVersion)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("DocumentVersion");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.DocumentVersionApproval.DetailsClass.IImplementation.Approver
        {
            get
            {
                return this.Approver;
            }
            set
            {
                this.Approver = (global::LightSwitchApplication.Implementation.Employee)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Approver");
                }
            }
        }
        
        partial void OnDocumentVersionApproval_DocumentVersionChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("DocumentVersion");
            }
        }
        
        partial void OnDocumentVersionApproval_EmployeeChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Approver");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class DocumentVersionHolder :
        global::LightSwitchApplication.DocumentVersionHolder.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.DocumentVersionHolder.DetailsClass.IImplementation.DocumentVersion
        {
            get
            {
                return this.DocumentVersion;
            }
            set
            {
                this.DocumentVersion = (global::LightSwitchApplication.Implementation.DocumentVersion)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("DocumentVersion");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.DocumentVersionHolder.DetailsClass.IImplementation.CopyHolder
        {
            get
            {
                return this.CopyHolder;
            }
            set
            {
                this.CopyHolder = (global::LightSwitchApplication.Implementation.Employee)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("CopyHolder");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.DocumentVersionHolder.DetailsClass.IImplementation.DocumentVersionReviews
        {
            get
            {
                return this.DocumentVersionReviews;
            }
        }
        
        partial void OnDocumentVersionHolder_DocumentVersionChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("DocumentVersion");
            }
        }
        
        partial void OnDocumentVersionHolder_EmployeeChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("CopyHolder");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class DocumentVersionReview :
        global::LightSwitchApplication.DocumentVersionReview.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.DocumentVersionReview.DetailsClass.IImplementation.DocumentVersionHolder
        {
            get
            {
                return this.DocumentVersionHolder;
            }
            set
            {
                this.DocumentVersionHolder = (global::LightSwitchApplication.Implementation.DocumentVersionHolder)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("DocumentVersionHolder");
                }
            }
        }
        
        partial void OnDocumentVersionReview_DocumentVersionHolderChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("DocumentVersionHolder");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class DocumentVersion :
        global::LightSwitchApplication.DocumentVersion.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.DocumentVersion.DetailsClass.IImplementation.Document
        {
            get
            {
                return this.Document;
            }
            set
            {
                this.Document = (global::LightSwitchApplication.Implementation.Document)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Document");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.DocumentVersion.DetailsClass.IImplementation.Author
        {
            get
            {
                return this.Author;
            }
            set
            {
                this.Author = (global::LightSwitchApplication.Implementation.Employee)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Author");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.DocumentVersion.DetailsClass.IImplementation.DocumentVersionApprovals
        {
            get
            {
                return this.DocumentVersionApprovals;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.DocumentVersion.DetailsClass.IImplementation.DocumentVersionHolders
        {
            get
            {
                return this.DocumentVersionHolders;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.DocumentVersion.DetailsClass.IImplementation.ChangeRequests
        {
            get
            {
                return this.ChangeRequests;
            }
        }
        
        partial void OnDocumentVersion_DocumentChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Document");
            }
        }
        
        partial void OnDocumentVersion_EmployeeChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Author");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Employee :
        global::LightSwitchApplication.Employee.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.Documents
        {
            get
            {
                return this.Documents;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.DocumentVersions
        {
            get
            {
                return this.DocumentVersions;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.DocumentVersionHolders
        {
            get
            {
                return this.DocumentVersionHolders;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.DocumentVersionApprovals
        {
            get
            {
                return this.DocumentVersionApprovals;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.ChangeRequests
        {
            get
            {
                return this.ChangeRequests;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
}

